const steps=[['Intake request','Supervisor accepted the brief and loaded workspace context.','Supervisor','complete','09:42:18'],['Build execution plan','Ordered dependency-aware plan created from the request.','Supervisor','complete','09:42:22'],['Retrieve long-term memory','Found a similar competitor memo; plan changed to reuse its source rubric.','Memory system','complete','09:42:25'],['Research competitors','Specialists execute web_search and source retrieval in parallel.','Research specialists','active','09:43:01'],['Review research output','Reviewer rejected one unsupported claim and sent it back for rework.','Reviewer','warn','Send-back'],['Human approval','Sensitive external operation paused until a human responds.','Approval queue','warn','Waiting'],['Synthesize and deliver','Resume after approval, synthesize, quality-check, and deliver.','Writing specialist','pending','Blocked']];
const events=[['intake','task_started','request accepted'],['planning','decompose','ordered plan: 4 dependent subtasks'],['memory','retrieve','similar task found: competitor memo'],['planning','plan_changed','added source-quality rubric from memory'],['research','web_search','3 specialist tool calls running'],['review','reject','unsupported pricing claim'],['review','send_back','feedback sent to research specialist'],['approval','escalate','sensitive-operation trigger fired'],['approval','paused','waiting for human response']];
const $=s=>document.querySelector(s),list=$('#stepList'),stream=$('#traceStream'),drawer=$('#approvalDrawer'),toast=$('#toast');
let selectedAction=-1,approvalState='pending';
function renderSteps(){list.innerHTML=steps.map((s,i)=>`<div class="step ${s[3]} ${selectedAction===i?'selected-action':''}" data-step="${i}"><div class="step-marker">${s[3]==='complete'?'✓':s[3]==='warn'?'!':i+1}</div><div class="step-body"><strong>${s[0]}</strong><p>${s[1]}</p></div><div class="step-meta"><span class="agent">${s[2]}</span><span class="status">${s[4]}</span></div></div>`).join('');document.querySelectorAll('[data-step]').forEach(el=>el.onclick=()=>{selectedAction=Number(el.dataset.step);$('#removeAction').disabled=selectedAction<0;$('#actionHint').textContent=`Selected: ${steps[selectedAction][0]}`;renderSteps()})}
function renderEvents(){stream.innerHTML=events.map((e,i)=>`<button class="trace-event ${i===events.length-1?'active':''}" data-event="${i}"><span class="bullet"></span><div><span class="time">${String(9+Math.floor(i/4)).padStart(2,'0')}:${String(42+i*2).padStart(2,'0')}</span><strong>${e[0]} · ${e[1]}</strong><small>${e[2]}</small></div></button>`).join('');$('#eventCount').textContent=events.length;document.querySelectorAll('[data-event]').forEach(el=>el.onclick=()=>{const e=events[Number(el.dataset.event)];$('#traceDetail').innerHTML=`<span class="eyebrow">EVENT DETAIL</span><strong>${e[0]} · ${e[1]}</strong><p>${e[2]}</p><small>Decision node ${Number(el.dataset.event)+1} · recorded in RUN-7F3A</small>`})}
function notify(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
renderSteps();renderEvents();setTimeout(()=>drawer.classList.add('open'),1100);
$('#approvalNav').onclick=()=>{drawer.classList.add('open');notify('Approval checkpoint opened')};$('#closeDrawer').onclick=()=>drawer.classList.remove('open');
function resolveApproval(mode){approvalState=mode;drawer.classList.remove('open');steps[5][3]='complete';steps[5][4]=mode==='approved'?'Approved':'Taken over';steps[6][3]='active';steps[6][4]=mode==='approved'?'Resuming':'Human-led';events.push(['approval',mode==='approved'?'approved':'take_over',mode==='approved'?'human approved sensitive operation':'human took control of the operation']);events.push(['synthesis','resume','workflow resumed after human response']);renderSteps();renderEvents();$('#runMeta').textContent=mode==='approved'?'Started 09:42:18 · approved · workflow resumed':'Started 09:42:18 · taken over · workflow resumed';$('#approvalNav').innerHTML='<span>◌</span> Human approval <b class="resolved-count">✓</b>';$('#approvalEyebrow').textContent='RESOLVED';$('#approvalTitle').textContent=mode==='approved'?'Operation approved':'Human takeover recorded';notify(mode==='approved'?'Approved. Workflow resumed and synthesis is running.':'Take over recorded. Workflow resumed under human control.')}
$('#approveBtn').onclick=()=>resolveApproval('approved');$('#takeoverBtn').onclick=()=>resolveApproval('takeover');
$('#addAction').onclick=()=>{const i=steps.length+1;steps.splice(5,0,['New action','Custom action added to the demo execution plan.','Supervisor','pending','Added']);selectedAction=5;$('#actionHint').textContent='Selected: New action';renderSteps();notify('Action added to the execution plan.')};$('#removeAction').onclick=()=>{if(selectedAction<0||steps.length<=1)return;const removed=steps.splice(selectedAction,1)[0];selectedAction=-1;$('#removeAction').disabled=true;$('#actionHint').textContent='Select an action to edit the plan';renderSteps();notify(`${removed[0]} removed from the plan.`)};
